CREATE TABLE LOP(
    MALOP VARCHAR(255) NOT NULL PRIMARY KEY ,
    TENLOP VARCHAR(255) NOT NULL,
    KHOAHOC INTEGER NOT NULL,
    GVCN VARCHAR(255) NOT NULL
);

INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT1', "AT18C", 1, "Trần Thanh Tùng");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT2', "AT18C", 3, "Trần Quốc Tuấn");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT3', "AT18C", 2, "Lê Duy Hiển");
INSERT INTO LOP(MALOP, TENLOP, KHOAHOC, GVCN) VALUES ('AT4', "AT18C", 4, "Nông Việt Hoàng");

CREATE TABLE HOSO(
    MAHS VARCHAR(255) NOT NULL PRIMARY KEY ,
    HOTEN VARCHAR(255) NOT NULL,
    NGAYSINH DATE,
    DIACHI VARCHAR(255) NOT NULL,
    LOP VARCHAR(255) NOT NULL,
    DIEMTOAN FLOAT,
    DIEMLY FLOAT,
    DIEMHOA FLOAT
);

INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS1', "Nguyễn Ngọc Anh", "2003-1-21", "Quảng Ninh", "AT18C", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS2', "Lê Minh Khôi", "2003-3-12", "Quảng Ninh", "AT18C", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS3', "Hoàng Tuyển Quyền", "2003-8-6", "Quảng Ninh", "AT18C", 9, 8, 10);
INSERT INTO HOSO(MAHS, HOTEN, NGAYSINH, DIACHI, LOP, DIEMTOAN, DIEMLY, DIEMHOA) VALUES ('HS4', "Lê Đại Dương", "2003-5-4", "Argentina", "AT18E", 9, 8, 10);

